import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./_component/Header";
import { Roboto } from "next/font/google";
import ReduxComponent from "./_component/ReduxComponent";

const Metadata: Metadata = {
  title: {
    default: "Cybersoft Shoes App",
    template: "%s | Cybersoft Shoes",
  },
  description:
    "Discover the latest collection of shoes in Cybersoft Shoes App. Find detailed descriptions and reviews for all products.",

  // OpenGraph (Facebook, Zalo, LinkedIn…)
  openGraph: {
    title: "Cybersoft Shoes App – Latest Shoe Collection",
    description:
      "Shop the latest shoes collection with detailed reviews on Cybersoft Shoes App.",
    url: "https://bc84-nextjs-ts-vjf5.vercel.app/",
    siteName: "Cybersoft Shoes App",
    images: [
      {
        url: "https://apistore.cybersoft.edu.vn/images/converse-chuck-taylor.png",
        width: 800,
        height: 600,
        alt: "Latest Shoes Collection",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: "Cybersoft Shoes App – Latest Shoe Collection",
    description:
      "Discover and shop the latest shoes collection with detailed reviews.",
    images: [
      "https://apistore.cybersoft.edu.vn/images/van-old-school.png",
    ],
    creator: "@cybersoft",
  },

  // Favicon và manifest
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",

  // JSON-LD schema.org (dùng metadata.other để nhúng)
  other: {
    "script:type=application/ld+json": JSON.stringify({
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Cybersoft Shoes App",
      description:
        "Discover and shop the latest collection of shoes on Cybersoft Shoes App.",
      url: "https://yourdomain.com",
    }),
  },
};


const robotoFont = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  // variable: '--font-roboto',
});
//xoá import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="preload" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossOrigin="anonymous"></link>
        <title>Cybersoft Shoes App</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${robotoFont.className}`}>
        <ReduxComponent>
          <Header />
          {children}
        </ReduxComponent>



        <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}




