import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./_component/Header";
import { Roboto } from "next/font/google";
import ReduxComponent from "./_component/ReduxComponent";



const robotoFont = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  // variable: '--font-roboto',
});
//xoá import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossOrigin="anonymous"></link>
        <title>Cybersoft Shoes App</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${robotoFont.className}`}>
        <ReduxComponent>
          <Header />
          {children}
        </ReduxComponent>



        <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}




